version: '2'



services:
  nginx:
     build: ./nginx
     container_name: nginx
     restart: always
     ports:
     - 80:80
     - 443:443
     volumes:
       - ./nginx/www:/usr/share/nginx/html
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
       - ./nginx/log/error.log:/var/log/nginx/error.log

  redis:
      build: ./redis
      expose:
        - "6379"
      volumes:
        - ./redis/redis.conf:/usr/local/redis/redis.conf
        - ./redis/redis.log:/usr/local/redis/redis.log
      restart: always
      container_name: redis

  search-movie:
      image: wangxucode1991/search-movie
      restart: always
      container_name: search-movie
      hostname: search-movie
      expose:
        - "8081"
      command:
      - "--mongodb.address=192.168.10.233"
      depends_on:
        - nginx
        - redis
